### ISSUE TITLE
Application crashes after proximity sensor turns the display on

### ISSUE THREAD

**Issue by segrey11** [datso/react-native-pjsip-app#15]
Hi.
I made a call and brought my device to the ear then proximity sensor  turned off the display. After I take the phone away from the ear proximity sensor was supposed to enable display but application crashed. 
Tested on Motorola MotoX play android 6.0.2. 
Found an error in logcat:
```
07-06 23:43:00.513 370-12891/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
07-06 23:43:00.514 370-12891/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
07-06 23:43:00.546 370-12891/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
07-06 23:43:00.546 370-12891/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
07-06 23:43:00.546 370-12891/? E/mm-camera: la_hist_trigger_update: luma target from AEC = 0! use default LA curve
07-06 23:43:00.547 370-12889/? E/mm-camera: awb_port_update_awb_info AWB Decision is not valid. Dont send metadata
07-06 23:43:00.549 370-12891/? D/mm-camera: bg_stats_pdaf_align: camif:(2560x1920) pdaf:(160,160) bg_rgn:(40,40) binning=2
07-06 23:43:00.552 370-12891/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
07-06 23:43:00.552 370-12891/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
07-06 23:43:00.580 345-12882/? D/QCamera2HWI: void qcamera::QCamera2HardwareInterface::kpi_preview_stream_cb_routine(): CameraKpiTag: PREVIEW_START_TIME : 270
07-06 23:43:00.580 345-12882/? D/QCamera2HWI: [KPI Perf] static void qcamera::QCamera2HardwareInterface::preview_stream_cb_routine(mm_camera_super_buf_t*, qcamera::QCameraStream*, void*) : PROFILE_FIRST_PREVIEW_FRAME
07-06 23:43:00.585 11761-11761/? D/PjSipLogWriter: 23:43:00.585 os_core_unix.c !Info: possibly re-registering existing thread
07-06 23:43:01.254 4066-4568/? D/ClClient: Not sending keepalive.  Current connection state=STOPPED
07-06 23:43:01.388 12904-12904/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
07-06 23:43:01.389 12904-12904/? E/NEW_BHD: Cannot run on production devices!
07-06 23:43:02.537 11761-12729/? D/PjSipLogWriter: 23:43:02.536   Master/sound !Underflow, buf_cnt=0, will generate 1 frame
07-06 23:43:03.317 1692-5105/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=2063840, 192.168.0.1, [B8A3861915F5], RTM_NEWNEIGH, NUD_PROBE}
07-06 23:43:05.002 425-425/? I/MSM-irqbalance: Decided to move IRQ84 from CPU7 to CPU6
07-06 23:43:05.562 1692-3026/? E/MotoSensors: Proximity covered 1
07-06 23:43:05.573 11761-11761/? D/PjSipBroadcastReceiver: Received "com.carusto.call.screen.locked" response from service ({"lock":true})
07-06 23:43:05.613 345-930/? D/AudioFlinger: mixer(0xb408f008) throttle end: throttle time(2)
07-06 23:43:05.763 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:05.884 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:05.998 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.124 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.238 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.359 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.423 12907-12907/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
07-06 23:43:06.424 12907-12907/? E/NEW_BHD: Cannot run on production devices!
07-06 23:43:06.476 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.596 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.720 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:06.804 1692-3026/? E/MotoSensors: Proximity uncovered
07-06 23:43:06.812 11761-11761/? D/PjSipBroadcastReceiver: Received "com.carusto.call.screen.locked" response from service ({"lock":false})
07-06 23:43:10.003 425-425/? I/MSM-irqbalance: Decided to move IRQ178 from CPU4 to CPU6
07-06 23:43:10.718 1692-3033/? V/AlarmManager: sending alarm {ef186b8 type 2 *walarm*:com.google.android.location.ALARM_WAKEUP_LOCATOR}
07-06 23:43:10.721 1692-3033/? V/AlarmManager: sending alarm {364b51b type 3 *alarm*:com.google.android.gms/.lockbox.LockboxAlarmReceiver}
07-06 23:43:10.737 1692-3868/? D/WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@d57a676}
07-06 23:43:10.754 1692-1692/? V/AlarmManager: done {ef186b8, *walarm*:com.google.android.location.ALARM_WAKEUP_LOCATOR} [36ms]
07-06 23:43:10.764 1692-1692/? V/AlarmManager: done {364b51b, *alarm*:com.google.android.gms/.lockbox.LockboxAlarmReceiver} [46ms]
07-06 23:43:11.254 4066-4568/? D/ClClient: Not sending keepalive.  Current connection state=STOPPED
07-06 23:43:11.459 12917-12917/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
07-06 23:43:11.460 12917-12917/? E/NEW_BHD: Cannot run on production devices!
07-06 23:43:12.411 1692-3026/? E/MotoSensors: Proximity covered 1
07-06 23:43:12.420 11761-11761/? D/PjSipBroadcastReceiver: Received "com.carusto.call.screen.locked" response from service ({"lock":true})
                                                           
                                                           --------- beginning of crash
07-06 23:43:12.441 11761-11778/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.pjapp, PID: 11761
                                                   com.facebook.react.uimanager.IllegalViewOperationException: Node is not attached to a parent: 820
                                                       at com.facebook.react.uimanager.UIImplementation.replaceExistingNonRootView(UIImplementation.java:402)
                                                       at com.facebook.react.uimanager.UIManagerModule.replaceExistingNonRootView(UIManagerModule.java:312)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)
07-06 23:43:12.443 1692-5884/? W/ActivityManager:   Force finishing activity com.pjapp/.MainActivity
07-06 23:43:12.444 1692-5884/? I/ActivityManager: moveHomeStack, setupComplete:true
07-06 23:43:12.468 1692-12919/? W/DropBoxManagerService: Dropping: data_app_crash (1148 > 0 bytes)
07-06 23:43:12.509 11761-11791/? D/PjSipService: Handle "com.carusto.app.hidden" action (empty extras)
07-06 23:43:12.570 1692-10303/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-06 23:43:12.579 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:12.601 1692-3026/? E/MotoSensors: Proximity covered 2
07-06 23:43:12.606 1692-1761/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{9efbc29 u0 com.carusto.call.screen.locked} to ReceiverList{d8c2e0d 11761 com.pjapp/10171/u0 remote:70c0a4}: process crashing
07-06 23:43:12.649 1692-1704/? I/art: Background partial concurrent mark sweep GC freed 62764(3MB) AllocSpace objects, 0(0B) LOS objects, 32% free, 32MB/48MB, paused 2.163ms total 171.203ms
07-06 23:43:12.699 308-681/? I/SFPerfTracer:      triggers: (rate: 0:0) (389 sw vsyncs) (0 skipped) (820:56574 vsyncs) (822:57323)
07-06 23:43:12.701 370-12876/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
07-06 23:43:12.753 3875-4648/? W/TabTreeCopier: Card found with UNKNOWN_TAB, Entry Type 155
07-06 23:43:12.754 3875-4648/? W/TabTreeCopier: Card found with UNKNOWN_TAB, Entry Type 143
07-06 23:43:12.756 3875-4648/? W/TabTreeCopier: Card found with UNKNOWN_TAB, Entry Type 150
07-06 23:43:12.947 1692-3157/? D/WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@d57a676}
07-06 23:43:12.959 1692-6506/? D/LBSSystemMonitorService: handleMessage what - 7
07-06 23:43:12.959 1692-6506/? D/Wiper_jni: Send Passive Location.
07-06 23:43:12.975 4081-8735/? I/Places: Converted 7 out of 9 WiFi scans
07-06 23:43:13.087 1692-3026/? E/MotoSensors: Proximity uncovered
07-06 23:43:13.088 4081-6691/? I/GCoreUlr: Successfully inserted 1 locations
07-06 23:43:13.090 1692-1761/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{3b6112 u0 com.carusto.call.screen.locked} to ReceiverList{d8c2e0d 11761 com.pjapp/10171/u0 remote:70c0a4}: process crashing
```

**Comment by real1988** [comment]
Hi,How do you solve this problem?
