### ISSUE TITLE
App won't load with the latest version of PJSIP 2.7.1

### ISSUE THREAD

**Issue by mattyleggy** [datso/react-native-pjsip-app#29]
I was unable to get the latest version of this app to build onto my phone. It would begin loading but the application would always crash without opening on the phone. I had to downgrade the version of PJSIP to 2.7.0 by using `npm install --save react-native-pjsip@2.7.0` and then `react-native link` and removing the duplicate entries in the `MainApplication.java` file. After doing this the application launches and runs fine.

**Comment by real1988** [comment]
can you hlep me ???    I'm the same as your problem, but not yet.



02-07 13:41:05.049: E/memtrack(6336): Couldn't load memtrack module (No such file or directory)
02-07 13:41:05.049: E/android.os.Debug(6336): failed to load memtrack module: -2
02-07 13:41:07.459: E/memtrack(6350): Couldn't load memtrack module (No such file or directory)
02-07 13:41:07.459: E/android.os.Debug(6350): failed to load memtrack module: -2
02-07 13:41:09.239: E/memtrack(6380): Couldn't load memtrack module (No such file or directory)
02-07 13:41:09.239: E/android.os.Debug(6380): failed to load memtrack module: -2
02-07 13:41:10.919: E/dalvikvm(6390): dlopen("/data/app-lib/com.pjsip-2/libpjsua2.so") failed: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 13:41:10.919: E/PjSipService(6390): Error while loading PJSIP pjsua2 native library
02-07 13:41:10.919: E/PjSipService(6390): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 13:41:10.919: E/PjSipService(6390): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
02-07 13:41:10.919: E/PjSipService(6390): 	at java.lang.System.loadLibrary(System.java:526)
02-07 13:41:10.919: E/PjSipService(6390): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:129)
02-07 13:41:10.919: E/PjSipService(6390): 	at com.carusto.ReactNativePjSip.PjSipService.access$100(PjSipService.java:52)
02-07 13:41:10.919: E/PjSipService(6390): 	at com.carusto.ReactNativePjSip.PjSipService$2.run(PjSipService.java:235)
02-07 13:41:10.919: E/PjSipService(6390): 	at android.os.Handler.handleCallback(Handler.java:733)
02-07 13:41:10.919: E/PjSipService(6390): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 13:41:10.919: E/PjSipService(6390): 	at android.os.Looper.loop(Looper.java:136)
02-07 13:41:10.919: E/PjSipService(6390): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-07 13:41:10.919: E/AndroidRuntime(6390): FATAL EXCEPTION: PjSipService
02-07 13:41:10.919: E/AndroidRuntime(6390): Process: com.pjsip, PID: 6390
02-07 13:41:10.919: E/AndroidRuntime(6390): java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:132)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at com.carusto.ReactNativePjSip.PjSipService.access$100(PjSipService.java:52)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at com.carusto.ReactNativePjSip.PjSipService$2.run(PjSipService.java:235)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at android.os.Handler.handleCallback(Handler.java:733)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at android.os.Looper.loop(Looper.java:136)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-07 13:41:10.919: E/AndroidRuntime(6390): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at java.lang.System.loadLibrary(System.java:526)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:129)
02-07 13:41:10.919: E/AndroidRuntime(6390): 	... 6 more

**Comment by real1988** [comment]
How can I do???

**Comment by mattyleggy** [comment]
That appears to be a different issue to the one I had. What device are you running on?

**Comment by tuledev** [comment]
I have got this issue also. It appears on android 4.x devices
